framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    session: false
    cache:
        app: cache.adapter.filesystem
    assets: false
    csrf_protection: false
    profiler:
        enabled: false
    router:
        enabled: false
    annotations:
        enabled: false
    serializer:
        enabled: true
    translator:
        enabled: false
    mailer:
        enabled: false
    rate_limiter:
        enabled: false