name: Compile marathon binary

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: PHPUnit permissions
        run: chmod +x ./bin/phpunit

      - name: Run PHPUnit
        run: ./bin/phpunit

      - name: Install Box builder
        run: composer global require humbug/box

      - name: Run the build
        run: box compile

      - name: Test marathon binary
        run: php marathon list

      - name: Check infinite loop
        run: |
            INFINITE_LOOP=$(if [ "${{ github.actor }}" == 'GitHub Action' ]; then echo 'true'; else echo 'false'; fi)
            echo "INFINITE_LOOP=$INFINITE_LOOP" >> $GITHUB_ENV

      - name: Get branch name
        if: ${{ env.INFINITE_LOOP == 'false' }}
        run: |
            BRANCH=${GITHUB_REF#refs/heads/}
            echo "BRANCH=$BRANCH" >> $GITHUB_ENV
      
      - name: Get username
        if: ${{ env.INFINITE_LOOP == 'false' && env.BRANCH != 'main' }}
        run: |
            USERNAME="$(git log -n 1 --pretty=format:%an)"
            echo "USERNAME=$USERNAME" >> $GITHUB_ENV
      
      - name: Get email
        if: ${{ env.INFINITE_LOOP == 'false' && env.BRANCH != 'main' }}
        run: |
            EMAIL=$(git log -n 1 --pretty=format:%ae)
            echo "EMAIL=$EMAIL" >> $GITHUB_ENV

      - name: Commit new marathon binary
        if: ${{ env.INFINITE_LOOP == 'false' && env.BRANCH != 'main' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: ${{ env.BRANCH }}/compilation
            commit_user_name: ${{ env.USERNAME }}
            commit_user_email: ${{ env.EMAIL }}
