name: Compile marathon binary

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Install Box builder
        run: composer global require humbug/box

      - name: Run the build
        run: box compile

      - name: Test marathon binary
        run: php marathon list

      - name: Check infinite loop
        id: skip-check
        run: echo "SKIP_CHECK=$(if [ "${{ github.actor }}" == "GitHub Action" ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_ENV

      - name: Afficher SKIP_CHECK
        run: echo "SKIP_CHECK is $SKIP_CHECK"

      - name: Check if Pull Request
        id: pr-check
        run: echo "IS_PR=$(if [ "${{ github.event_name }}" == "pull_request" ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_ENV

      - name: Afficher IS_PR
        run: echo "IS_PR is $IS_PR"

      - name: Check infinite loop
        id: skip-infinite-loop-check
        run: echo "SKIP_INFINITE_LOOP_CHECK=$(if [ "${{ github.actor }}" == "GitHub Action" ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_ENV

      - name: Check if Pull Request
        id: pr-check
        run: echo "IS_PR=$(if [ "${{ github.event_name }}" == "pull_request" ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_ENV

      - name: Configure Git
        if: steps.pr-check.outputs.IS_PR == 'true' && steps.skip-check.outputs.SKIP_INFINITE_LOOP_CHECK != 'true'
        run: |
            git config user.name "$(git log -n 1 --pretty=format:%an)"
            git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Commit and Push Binary
        if: steps.pr-check.outputs.IS_PR == 'true' && steps.skip-check.outputs.SKIP_INFINITE_LOOP_CHECK != 'true'
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          git add ./marathon
          git commit -m "$branch_name/compilation"
          git push origin HEAD:$branch_name
