name: Compile marathon binary

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install

      - name: Install Box builder
        run: composer global require humbug/box

      - name: Run the build
        run: box compile

      - name: Test marathon binary
        run: php marathon list

      - name: Check if push new marathon binary
        id: push-it
        run: |
            CONDITION=$(if [ "${{ github.event_name }}" == 'pull_request' ]; then if [ "${{ github.actor }}" == 'GitHub Action' ]; then echo 'false'; else echo 'true'; fi; else echo 'false'; fi)
            echo "CONDITION=$CONDITION" >> $GITHUB_ENV

      - name: Afficher PUSH_IT
        run: echo "PUSH_IT is $CONDITION"
      
      - name: Afficher CONDITION
        run: echo "CONDITION is $CONDITION"
        env:
            CONDITION: ${{ env.CONDITION }}

      - name: Configure Git
        if: steps.push-it.outputs.CONDITION == 'true'
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: Commit and Push Binary
        if: steps.push-it.outputs.CONDITION == 'true'
        run: |
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          git add ./marathon
          git commit -m "$branch_name/compilation"
          git push origin HEAD:$branch_name
